### ISSUE TITLE
Create icons for all selectable municipalities

### ISSUE THREAD

**Issue by juanfrans** [CenterForSpatialResearch/colombia_site#8]
Create icons for all selectable municipalities. This should be based on the total number of people affected. We could say initially that all municipalities with more than 50,000 affected people should be selectable. Affected people are the sum of displaced, arrived and internally displaced.

If this is too many or too few municipalities we can change the threshold.

**Comment by M-How** [comment]
Does this mean we need an icon wherever there is a 'node' that the paths draw to? I.e. an origin or a destination city for any path? Right now, the 28 icons are being drawn over cities that are hard coded in as a list in lines 310 to 340 of map.html file. Should I be adding more cities to this list? I'm not sure how Jevan generated this list...


<code>
//hard coded data
//[CITY,[LAT,LON],POPULATION]
var cities = [
  ["BOGOTÁ D.C.", [4.65052840264, -74.105971599], 6376000,],
  ["SANTIAGO DE CALI", [3.417586541, -76.5223324663],2040000],
  ["MEDELLÍN", [6.24894080931, -75.577055625699899], 2184000],
  ["SANTA MARÍA", [2.93902635801, -75.586686826999895],383991],
  ["VALLEDUPAR", [10.461893398500001, -73.258517044399895], 294731],
  ["BUENAVENTURA", [3.87547430591, -77.011535895500003], 290475] ,
  ["POPAYÁN", [2.4476985537, -76.6244690332],227840],
  ["SINCELEJO", [9.30045521524, -75.395996064399895],218430],
  ["TUMACO", [1.76133367771, -78.781544044499896], 203971],
  ["FLORENCIA", [1.61733394988, -75.606890209100001],163323],
  ["APARTADÓ", [7.88271669619, -76.626185972299893],114840],
  ["TURBO", [8.09409673761, -76.7264318309999], 163525],
  ["SAN FRANCISCO DE QUIBDO", [5.69234946496, -76.651124632600002], 100113],
  ["CIÉNAGA DE ORO", [8.87817659507, -75.622109338499897], 100908],
  ["EL CARMEN DE BOLÍVAR", [9.718034220970001, -75.121138832699899], 159987],
  ["SEGOVIA", [7.07992032695, -74.699300037499896], 40714],
  ["TIBÚ", [8.639717700409991, -72.735919371600005], 36502],
  ["MITÚ", [1.25114267922, -70.234986307900002], 14112],
  ["RIOSUCIO", [7.43338275367, -77.111109838], 57220],
  ["SAN PABLO", [7.47747543639, -73.924557832700003], 27108],
  ["EL CHARCO", [2.47697407881, -78.1102980565],28673],
  ["SAMANÁ", [5.41307433341, -74.9923802604999], 25649],
  ["ITUANGO", [7.17162301036, -75.76416656], 22952],
  ["INÍRIDA", [3.86469882092, -67.917962587700003], 17866],
  ["MUTATÁ", [7.24396317282, -76.436704695499898], 32500],
  ["SAN LUIS", [6.04286525408, -74.994392230900004], 11009],
  ["ARGELIA", [5.7315608939, -75.142715590500003], 10091],
  ["GRANADA", [3.5448713658, -73.706271300799898], 98824],
  ["RICAURTE (COLOSO)", [9.49099729992999, -75.3560877468], 6214]
];</code>

**Comment by juanfrans** [comment]
* Based on total people affected
* Use same buckets on the PDF
* Scale to where they are legible but distinguishable
* For all "clickable" municipalities

**Comment by M-How** [comment]
Icon size is now based off of "TOTAL_IMPACT" from TSV, uses same buckets as on PDF
